api_version = "2024-10"
name = "tracking-pixel"
uid = "5d23d7eb-259c-2ecc-9355-3be596a7ce72d9323f16"
type = "web_pixel_extension"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.api_url]
type = "single_line_text_field"
name = "API URL"
description = "Backend endpoint for tracking"