<?php

if (!defined('ABSPATH')) exit;

/**
 * Display Click ID in Admin Order view
 */
add_action('woocommerce_admin_order_data_after_billing_address', 'mv_display_order_click_id');
function mv_display_order_click_id($order): void {
    $order_id = $order->get_id();
    $click_id = get_post_meta($order_id, MONEVIBE_META_KEY, true);

    echo '<div style="background: #e7f5fe; padding: 12px; border-left: 4px solid #2096f3; margin-top: 20px; border-radius: 4px;">';
    if ($click_id) {
        echo '<h4 style="margin:0 0 5px 0;">' . esc_html__('Generated by monevibe', 'monevibe-tracker') . '</h4>';
        echo '<p style="margin:0;"><strong>' . esc_html__('Click ID:', 'monevibe-tracker') . '</strong> <code style="background:#fff; padding:2px 5px; border:1px solid #ccc;">' . esc_html($click_id) . '</code></p>';
    } else {
        echo '<p style="color:red; margin:0;"><strong>' . esc_html__('Monevibe Click ID:', 'monevibe-tracker') . '</strong> ' . esc_html__('Not found', 'monevibe-tracker') . '</p>';
    }
    echo '</div>';
}